### ISSUE TITLE
带 Operator 标记的词条无效？

### ISSUE THREAD

**Issue by millionart** [sfire/bl_ui_hanzify#1]
po里还有很多缺失的词条，官方对此有说法吗

**Comment by sfire** [comment]
目前的2.8仍处于开发阶段，很多词条都没能及时提取出来，所以会存在词条确实的状况。
我们可以先统计一下词条缺失的具体位置，等正式版发布后如果仍存在这样的状况的话，可以统一报给官方。
现有词条汉化才是当前最艰巨的任务。

**Comment by millionart** [comment]
所以带 Operator 标记的词条是确认无效的？

**Comment by sfire** [comment]
> 所以带 Operator 标记的词条是确认无效的？

不是的，operator应该是语境提取，专用在操作名称上的。不会是无效的词条。
有这种情况可以截图举例一下，我来看看。

**Comment by millionart** [comment]
几乎所有的 Operator 标记词条我翻译了都无效啊，比如 Move to Collection

**Comment by millionart** [comment]
是我搞错了

**Comment by sfire** [comment]
我试过了，没有问题。
![image](https://user-images.githubusercontent.com/5409756/56470545-dc382c00-6479-11e9-8a86-9de111aa4680.png)

不过如果发现其他UI汉化的问题，又或者有其他建议，也请继续反馈。
