### ISSUE TITLE
UV Editor - View

### ISSUE THREAD

**Issue by dmmocn** [sfire/bl_ui_hanzify#10]
对照截图：
![Snipaste_2019-07-15_12-04-46](https://user-images.githubusercontent.com/35016284/61202135-467b0880-a719-11e9-9d90-53a6462343d6.png)
![Snipaste_2019-07-15_12-05-14](https://user-images.githubusercontent.com/35016284/61202136-47139f00-a719-11e9-86dd-2275298d3aa2.png)
错误描述：
还是昨天frame的问题，查了一下，别的软件里frame有被翻译成【框显】的……
所以或许也可以这么翻译：
Frame Selected 【框显所选】
Frame All 【框显全部】
Frame All Fit 【框显完全匹配】

**Comment by sfire** [comment]
应该是上次遗漏了， a5d0cb95985968876d2145eb7d5a2d303fbe9102 已修正
