### ISSUE TITLE
编辑模式>选择

### ISSUE THREAD

**Issue by zhangzhengkang** [sfire/bl_ui_hanzify#12]
可以翻译成：去边界选择区域　或者　选择区域去边界
按过程来说是先选择了区域，再去除边界

![深度截图_选择区域_20190715195634](https://user-images.githubusercontent.com/39718415/61214647-0af13600-a73b-11e9-8896-9af601206417.png)
![深度截图_选择区域_20190715195654](https://user-images.githubusercontent.com/39718415/61214660-12184400-a73b-11e9-8488-2780399295d2.png)

**Comment by sfire** [comment]
词条缺失导致，后面会更新到之前提报的bug tracker中

**Comment by sfire** [comment]
我尝试在Blender 2.8 RC上复制你的现象，制作截图，但无法复制。。。
![图片](https://user-images.githubusercontent.com/5409756/61252370-e3788880-a78f-11e9-8ff0-6aee4c6f8e0c.png)
你能用下面的菜单查看一下你的版本信息吗？
![图片](https://user-images.githubusercontent.com/5409756/61252435-1b7fcb80-a790-11e9-98d0-59e29f33637a.png)
![图片](https://user-images.githubusercontent.com/5409756/61252506-54b83b80-a790-11e9-8c20-a41444ea2288.png)

**Comment by dmmocn** [comment]
这是edit mesh tools插件的功能

**Comment by zhangzhengkang** [comment]
好吧，我错了，edit mesh tool插件的功能，作者把菜单挪出来，我还以为内置功能了
