### ISSUE TITLE
编辑模式>网格>法向

### ISSUE THREAD

**Issue by zhangzhengkang** [sfire/bl_ui_hanzify#13]
这里菜单翻译是矢量，工具提示里是法向，不统一

![深度截图_选择区域_20190715200454](https://user-images.githubusercontent.com/39718415/61214998-1133e200-a73c-11e9-8bba-ebe202a38817.png)

**Comment by sfire** [comment]
这里没有毛病，`Normal` --> `法向`，`Vector` --> `矢量`
