### ISSUE TITLE
编辑模式>顶点>挂钩

### ISSUE THREAD

**Issue by zhangzhengkang** [sfire/bl_ui_hanzify#14]
这里挂钩与钩挂不统一，一级菜单是挂钩，修改器是钩挂，二级菜单的＂钩挂到＂还好

![深度截图_选择区域_20190715200826](https://user-images.githubusercontent.com/39718415/61215265-ef872a80-a73c-11e9-93ab-430034b1e314.png)
![深度截图_选择区域_20190715200842](https://user-images.githubusercontent.com/39718415/61215269-f31ab180-a73c-11e9-9583-afba96814c45.png)

**Comment by sfire** [comment]
这里由于用了复数，所以当作名词翻译的，但改为钩挂也并无不妥，稍后修正提交。

**Comment by sfire** [comment]
a5d0cb95985968876d2145eb7d5a2d303fbe9102 已修正
