### ISSUE TITLE
渲染>EEVEE>辉光

### ISSUE THREAD

**Issue by zhangzhengkang** [sfire/bl_ui_hanzify#18]
这里的knee是指在阈值的基础上给阈值一个微小的增减的范围，类似给阈值微调的意思，
是不是可以翻译成　微调　或者　摆动

![深度截图_选择区域_20190719205940](https://user-images.githubusercontent.com/39718415/61536933-6cc9dc80-aa68-11e9-9281-12f9221a3e73.png)

**Comment by sfire** [comment]
了解了一下，术语就是屈伸度，tooltip有描述，应该不影响使用。
