### ISSUE TITLE
Eevee - 点光 - 阴影 - 指数

### ISSUE THREAD

**Issue by dmmocn** [sfire/bl_ui_hanzify#21]
Eevee引擎下，物体模式，选中点光源，在属性面板的【物体数据】选项卡——【阴影】——【指数】的注释错了
![Snipaste_2019-07-25_00-03-00](https://user-images.githubusercontent.com/35016284/61809427-dc2c3b80-ae6f-11e9-9361-0c0335a5a6ca.png)
![Snipaste_2019-07-25_00-03-48](https://user-images.githubusercontent.com/35016284/61809511-067df900-ae70-11e9-9f0f-d6988e8d8674.png)
应该改成是：
【阴影缓冲指数.】
【在指数阴影映射（ESM）降低灯光出血的偏移量.】

**Comment by sfire** [comment]
7e6821c4ae2fbb658053194269eccd16d5a91b0b 已提交修改
