### ISSUE TITLE
灯光节点汉化翻译疑问

### ISSUE THREAD

**Issue by 1129915719** [sfire/bl_ui_hanzify#22]
![QEA4WNRO F{GRQ2CJV)YT1C](https://user-images.githubusercontent.com/41713871/62470968-24335280-b7ce-11e9-861b-bba53b10aae0.png)
![GVG59}8NIBHKG}K{P2}UU%8](https://user-images.githubusercontent.com/41713871/62470972-24cbe900-b7ce-11e9-8c61-560a70d58782.png)
光线衰减   平方型    线性    常植

**Comment by 1129915719** [comment]
![chrome_2019-08-05_22-16-15](https://user-images.githubusercontent.com/41713871/62471171-ae7bb680-b7ce-11e9-9576-f7deadef7687.png)
正确

**Comment by sfire** [comment]
29043eeb59dd55c4bf63625ffa3c0e38b4bacb4b 已修正为`二次型`
