### ISSUE TITLE
蜡笔编辑模式>笔画，翻译不准确

### ISSUE THREAD

**Issue by KassadinL** [sfire/bl_ui_hanzify#26]
<img width="134" alt="Annotation 2019-09-01 202900" src="https://user-images.githubusercontent.com/19602109/64076430-74330580-ccf7-11e9-9eae-49a83fe2e99d.png">
<img width="175" alt="Annotation 2019-09-01 20248" src="https://user-images.githubusercontent.com/19602109/64076431-74cb9c00-ccf7-11e9-81ac-6f0a7ea0a531.png">

位置：蜡笔编辑模式>笔画，标题栏，笔画菜单

倒数第四个功能“Close”，目前翻译为“临近”，应该为“闭合”
倒数第二个功能“Toggle Caps”，目前翻译为“切换大小写”，应该为“切换封顶形状”

**Comment by sfire** [comment]
已经[修正](https://developer.blender.org/rBTS5049)
