### ISSUE TITLE
融球相关面板词条建议

### ISSUE THREAD

**Issue by Rindbee** [sfire/bl_ui_hanzify#28]
侧栏变换面板，以及物体数据活动元素面板。

1、类型选择器，这里指底层结构类型。
       建议详细细分，可用结构类型。
2、其中可选项：球(Ball)和胶囊(Capsule)并非底层结构，建议使用点(Point)和直线段(Line)代替。

**Comment by sfire** [comment]
这个不是汉化能解决的，建议到[这里](https://blender.community/c/rightclickselect/) 提建议。
