### ISSUE TITLE
Lookdev 的翻译问题

### ISSUE THREAD

**Issue by millionart** [sfire/bl_ui_hanzify#3]
这个人担任相关高级职位并对这个词有解释，我相信是比较专业的，可以参考下

https://www.zhihu.com/question/48366815

http://www.linecg.com/news_8284.html

> 先说说中文翻译，我认为应该翻译成 “外观开发”—— 虽然看到很多地方翻译成 “视觉开发”（比如动物世界的字幕以及 Foundery Katana 的中文官方网站，这个翻译嘈点，小编也想吐槽），但较真的讲的话，并不妥。首先，有一个前期概念设计阶段的工种 “Visual Development”，在很多地方也被翻译成 “视觉发开”，单从字面意思上，visual 比 look 更加适合 “视觉”。Look Development 在某些公司，尤其是偏动画电影的公司 —— 比如 Animal Logic（乐高大电影系列，彼得兔）、Illumination Entertainment（小黄人系列）、国内的追光动画 —— 又被称为 Surfacing，顾名思义也是表面、外观之意。

**Comment by xc1988** [comment]
我觉得针对功能效果来看直接翻译成快速预览或者视觉预览，比较合适。
不管是翻译成外观开发还是视觉开发，总会让从英文版切换到中文的人看的一脸懵逼。

**Comment by sfire** [comment]
挂了几周了，没有更多人参与讨论，考虑到社区的意见，译为 `视觉预览` 吧。 e7b4598f0eabcc7a658bb93c47f8bd0286447c07
