### ISSUE TITLE
请求pull部分翻译

### ISSUE THREAD

**Issue by beyond-1234** [sfire/bl_ui_hanzify#31]
- 我翻译了一部分，翻译内容与路径如下
- 欢迎指出翻译不妥的地方，有些我也拿不准
- 如无问题我就新建一个pull请求

## 复制旋转约束
- Apply copied rotation before original, as if the constraint target is a parent
- :src: bpy.types.CopyRotationConstraint.mix_mode:'BEFORE'
- 在初始旋转前应用复制旋转，仿佛目标物体为原物体的父级
- 
- Apply copied rotation after original, as if the constraint target is a - child
- :src: bpy.types.CopyRotationConstraint.mix_mode:'AFTER'
- 在初始旋转后应用复制旋转，仿佛目标物体为原物体的子级

## 复制变换约束
- Specify how the copied and existing transformations are combined
- :src: bpy.types.CopyTransformsConstraint.mix_mode
- 指定复制变换和初始变换的组合方式
- 
- Apply copied transformation before original, as if the constraint target is a parent. Scale is handled specially to avoid creating shear
- :src: bpy.types.CopyTransformsConstraint.mix_mode:'BEFORE'
- 在初始变换之前应用复制变换，仿佛约束物体为父级。特殊处理缩放防止出现撕裂
- 
- Apply copied transformation after original, as if the constraint target is a child. Scale is handled specially to avoid creating shear
- :src: bpy.types.CopyTransformsConstraint.mix_mode:'AFTER'
- 在初始变换之后应用复制变换，仿佛约束物体为父级。特殊处理缩放防止出现撕裂

## 保持体积约束

- 这里的free有一词多义问题，此处的意思应该是指明不受约束控制的轴向，所以下面对free和 non-free的翻译是不受控制和受控制。是否合适有待讨论:)
- 
- The way the constraint treats original non-free axis scaling
- :src: bpy.types.MaintainVolumeConstraint.mode
- 约束对受控轴向上缩放的处理方式
- 
- Volume is strictly preserved, overriding the scaling of non-free axes
- :src: bpy.types.MaintainVolumeConstraint.mode:'STRICT'
- 覆写受控制的轴向上的缩放来保持体积严格不变
- 
- Volume is preserved when the object is scaled uniformly. Deviations from uniform scale on non-free axes are passed through
- :src: bpy.types.MaintainVolumeConstraint.mode:'UNIFORM'
- 仅当物体按比例缩放时才保持体积不变。忽略受控制轴向在按比例缩放时导致的偏差
- 
- Volume is preserved when the object is scaled only on the free axis. Non-free axis scaling is passed through
- :src: bpy.types.MaintainVolumeConstraint.mode:'SINGLE_AXIS'
- 只有在当不受控制的轴向上缩放才保持体积不变。忽略受控制轴向上的缩放

## 缩裹修改器、缩裹约束

- The point is constrained to the surface of the target object, with distance offset always to the outside, towards or away from the original location
- :src: bpy.types.ShrinkwrapConstraint.wrap_mode:'OUTSIDE_SURFACE'
- :src: bpy.types.ShrinkwrapModifier.wrap_mode:'OUTSIDE_SURFACE'
- 被约束到目标物体的表面的顶点，总是使用相对于外侧的偏移距离，靠近或远离原位置

- The point is constrained to the surface of the target object, with distance offset applied exactly along the target normal
- :src: bpy.types.ShrinkwrapConstraint.wrap_mode:'ABOVE_SURFACE'
- :src: bpy.types.ShrinkwrapModifier.wrap_mode:'ABOVE_SURFACE'
- 被约束到目标物体的表面的顶点，沿目标物体法向使用偏移距离

## 变换约束

- Apply new rotation before original, as if it was on a parent
- :src: bpy.types.TransformConstraint.mix_mode_rot:'BEFORE'
- 在原始旋转之前应用新的旋转，仿佛目标物体是原物体的父级

- Apply new rotation after original, as if it was on a child
- :src: bpy.types.TransformConstraint.mix_mode_rot:'AFTER'
- 在原始旋转之后应用新的旋转，仿佛目标物体是原物体的子级

## eevee 日光

- How smooth is the transition between each cascade
- :src: bpy.types.SunLight.shadow_cascade_fade
- 每一层叠联阴影的平滑程度

- End distance of the cascaded shadow map (only in perspective view)
- :src: bpy.types.SunLight.shadow_cascade_max_distance
- 层叠阴影贴图的最大距离(仅用于正交视图)

- Angular diameter of the Sun as seen from the Earth
- :src: bpy.types.SunLight.angle
- 模拟从地球上看到日光的角直径

- Higher value increase resolution towards the viewpoint
- :src: bpy.types.SunLight.shadow_cascade_exponent
- 值越高，视窗中的解析度越高

## 光照探头

- Light Probe data-block for lighting capture objects
- :src: bpy.types.LightProbe
- 光线采集物体的光照探头数据块
  
- Probe clip end, beyond which objects will not appear in reflections
- :src: bpy.types.LightProbe.clip_end
- 探头裁剪终点，超过这个位置的物体将不会出现在反射中

- Probe clip start, below which objects will not appear in reflections
- :src: bpy.types.LightProbe.clip_start
- 探头裁剪起点，小于这个位置的物体将不会出现在反射中

- Control how fast the probe influence decreases
- :src: bpy.types.LightProbe.falloff
- 控制光照探头影响衰减的速率

- Number of sample along the x axis of the volume
- :src: bpy.types.LightProbe.grid_resolution_x
- 体积在x轴向采样的数量

- Number of sample along the y axis of the volume
- :src: bpy.types.LightProbe.grid_resolution_y
- 体积在y轴向采样的数量

- Number of sample along the z axis of the volume
- :src: bpy.types.LightProbe.grid_resolution_z
- 体积在z轴向采样的数量

- Modify the intensity of the lighting captured by this probe
- :src: bpy.types.LightProbe.intensity
- 修改这个光照探头采集的光照强度

- Lowest corner of the parallax bounding box
- :src: bpy.types.LightProbe.parallax_distance
- 视差边框的最低处

- Show captured lighting data into the 3D view for debugging purpose
- :src: bpy.types.LightProbe.show_data
- 在3D视图中展示采集的光照数据，用于调试

- Show the parallax correction volume in the 3D view
- :src: bpy.types.LightProbe.show_parallax
- 在3D视图中显示视差修正体积

- Volume used for precomputing indirect lighting
- :src: bpy.types.LightProbe.type:'GRID'
- 用于预先计算间接光照的体积

- Enable custom settings for the parallax correction volume
- :src: bpy.types.LightProbe.use_custom_parallax
- 启用视差修正体积的自定义设置

## 材质

- A pixel is rendered only if its alpha value is above this threshold
- :src: bpy.types.Material.alpha_threshold
- 仅当像素的Alpha值高于此阈值时才渲染像素

- Use the alpha threshold to clip the visibility (binary visibility)
- :src: bpy.types.Material.blend_method:'CLIP'
- :src: bpy.types.Material.shadow_method:'CLIP'
- 使用Alpha阈值决定可见性(二元可见性)

- Use noise to dither the binary visibility (works well with multi-samples)
- :src: bpy.types.Material.blend_method:'HASHED'
- 使用噪波方式丰富二元可见性(高采样量下效果好)

- True if this material has grease pencil data
- :src: bpy.types.Material.is_grease_pencil
- 当此材质拥有蜡笔的数据时为真

- The line color of a higher priority is used at material boundaries
- :src: bpy.types.Material.line_priority
- 材质边界使用优先级更高的线条颜色

- Approximate the thickness of the object to compute two refraction event (0 is disabled)
- :src: bpy.types.Material.refraction_depth
- 估算物体的厚度来计算二次折射结果(0为禁用)

- Use noise to dither the binary visibility and use filtering to reduce the noise
- :src: bpy.types.Material.shadow_method:'HASHED'
- 使用燥波方式丰富二元可见性并且使用过滤来减少噪点

- Limit transparency to a single layer (avoids transparency sorting problems)
- :src: bpy.types.Material.show_transparent_back
- 将透明效果限制为一层(避免透明层排序问题)

- Use the current world background to light the preview render
- :src: bpy.types.Material.use_preview_world
- 使用当前世界背景给预览渲染作为光照

## 粒子

- Emit particles from mesh with modifiers applied (must use same subsurf level for viewport and render for correct results)
- :src: bpy.types.ParticleSettings.use_modifier_stack
- 使用应用了修改器的网格发射粒子(视图和渲染必须使用相同的细分数才能获得正确的结果)

- Create random clumps around the parent
- :src: bpy.types.ParticleSettings.use_clump_noise
- 在父级周围创建随机聚集

**Comment by sfire** [comment]
以上词条已全部提交
