### ISSUE TITLE
法线修改器工具提示错误

### ISSUE THREAD

**Issue by beyond-1234** [sfire/bl_ui_hanzify#34]
混合系数的工具解释

How much of generated normals to mix with exiting ones

此处的'exiting'应为'existing'

**Comment by sfire** [comment]
所有UI译文的原文都是从代码里抓取出来的，与界面里显示的内容是一一对应关系。原文的拼写错误只会影响到英文界面的用户，我们理解意思之后，正常汉化即可。
有时候他们反应过来，会修正原文的。
