### ISSUE TITLE
你好，我为blender的PROrender渲染器做了汉化可以提交嘛？

### ISSUE THREAD

**Issue by SimonLuoshiping** [sfire/bl_ui_hanzify#36]
你好，我为blender的PROrender渲染器做了汉化可以提交嘛？我目前个人在用，我是基于blender.PO  翻译的节点都汉化好了

**Comment by sfire** [comment]
官方的这个汉化文件不会抓第三方插件的词条，所以这个插件的词条在官方的汉化文件中是不存在的，无法提交。
不过社区有一个小组在做第三方插件的汉化，已经有不少成果。有兴趣的话，加QQ群 983818187
