### ISSUE TITLE
Keymap - Image - Image(Global) - View Zoom Ratio

### ISSUE THREAD

**Issue by dmmocn** [sfire/bl_ui_hanzify#4]
![Snipaste_2019-07-15_11-31-49](https://user-images.githubusercontent.com/35016284/61194537-a9a67400-a6f4-11e9-997c-c5e746e9878d.png)
![Snipaste_2019-07-15_11-31-32](https://user-images.githubusercontent.com/35016284/61194538-aa3f0a80-a6f4-11e9-9536-314971679300.png)
【缩放比率视图】改成【视图缩放比率】

**Comment by dmmocn** [comment]
请问下，要是多个报错，是在同一个issues里跟帖报错，还是每个报错都要单开一个issues？有没有统一的格式呢？

**Comment by sfire** [comment]
已提交修正 f9252ca33f17b9cd6c58f5fa6df6b4e4804c2da5
关于你提到的报错格式的问题，建议按主题来报，然后集中处理。
格式的话，我的想法是这样的：

**修改器**：修改器及具体模式
**位置**：具体位于哪个选项卡/菜单/面板等
**问题描述及截图**：
**建议处理方式**：

**Comment by dmmocn** [comment]
OK，以后按照这个格式提交~
