### ISSUE TITLE
Keymap - Image - UV Editor

### ISSUE THREAD

**Issue by dmmocn** [sfire/bl_ui_hanzify#5]
### **Keymap - Image - UV Editor - Context Set Enum**
对照截图：
![Snipaste_2019-07-15_12-15-32](https://user-images.githubusercontent.com/35016284/61196201-7a493480-a6ff-11e9-9041-850beb2c42fd.png)
![Snipaste_2019-07-15_12-15-44](https://user-images.githubusercontent.com/35016284/61196205-7b7a6180-a6ff-11e9-9319-4ffb58a62f1f.png)
快捷键对应的功能是这个：
![Snipaste_2019-07-15_12-22-16](https://user-images.githubusercontent.com/35016284/61196190-6d2c4580-a6ff-11e9-9f4e-22b7592ec455.png)
修改建议：
context不知道怎么翻，有的地方翻译成【上下文】，有的地方翻译成【情境】，有的地方翻译成【正文】，貌似都不太好理解。是应该统一成【上下文】吗？

### **Keymap - Image - Image(Global) - Context Set**
对照截图：
![Snipaste_2019-07-15_13-17-34](https://user-images.githubusercontent.com/35016284/61196732-3a844c00-a703-11e9-8832-18577db9bc51.png)
![Snipaste_2019-07-15_13-17-00](https://user-images.githubusercontent.com/35016284/61196731-39ebb580-a703-11e9-977c-551cd1c0efb7.png)
快捷键对应的功能是这个：
![Snipaste_2019-07-15_13-18-25](https://user-images.githubusercontent.com/35016284/61196726-30624d80-a703-11e9-874a-6b03b046a976.png)
修改建议：
同上

**Comment by sfire** [comment]
`context` 全部统一为`上下文`，并提交修正 f9252ca33f17b9cd6c58f5fa6df6b4e4804c2da5
