### ISSUE TITLE
Keymap - Node Editor - Node Editor(Global)

### ISSUE THREAD

**Issue by dmmocn** [sfire/bl_ui_hanzify#6]
### **Keymap - Node Editor - Node Editor(Global) - Link Viewer**
对照截图：
![Snipaste_2019-07-15_14-04-01](https://user-images.githubusercontent.com/35016284/61197832-7a4e3200-a709-11e9-92a8-8617f621f07c.png)
![Snipaste_2019-07-15_14-04-22](https://user-images.githubusercontent.com/35016284/61197834-7ae6c880-a709-11e9-9548-0ff21736b8f3.png)
快捷键对应功能：
![Snipaste_2019-07-15_14-05-20](https://user-images.githubusercontent.com/35016284/61197861-9c47b480-a709-11e9-8102-476e424bc7ff.png)
修改建议：
【链接查看器】改成【连接预览器】

### **Keymap - Node Editor - Node Editor(Global) - Clear Viewer Border**
对照截图：
![Snipaste_2019-07-15_13-50-48](https://user-images.githubusercontent.com/35016284/61197634-a74e1500-a708-11e9-8e34-58e12775dc0d.png)
![Snipaste_2019-07-15_13-51-01](https://user-images.githubusercontent.com/35016284/61197636-a917d880-a708-11e9-9e29-d0920fbded9a.png)
快捷键对应功能：
![Snipaste_2019-07-15_14-00-11](https://user-images.githubusercontent.com/35016284/61197692-e41a0c00-a708-11e9-85a1-94fa34474d09.png)
修改建议：
【清除渲染选框】改成【清除预览器选框】

**Comment by sfire** [comment]
已提交修正 f9252ca33f17b9cd6c58f5fa6df6b4e4804c2da5
