### ISSUE TITLE
Keymap - Node Editor - Node Generic

### ISSUE THREAD

**Issue by dmmocn** [sfire/bl_ui_hanzify#7]
### **Keymap - Node Editor - Node Generic**
对照截图：
![Snipaste_2019-07-15_14-13-14](https://user-images.githubusercontent.com/35016284/61198139-175d9a80-a70b-11e9-95a9-87217eb202a1.png)
![Snipaste_2019-07-15_14-13-56](https://user-images.githubusercontent.com/35016284/61198140-17f63100-a70b-11e9-91b8-2c0c7554dde6.png)
修改建议：
Generic翻译成【通用操作】的比较多，可以统一一下

**Comment by sfire** [comment]
已提交修正 f9252ca33f17b9cd6c58f5fa6df6b4e4804c2da5
