### ISSUE TITLE
Keymap - Sequencer - Sequencer(Global)

### ISSUE THREAD

**Issue by dmmocn** [sfire/bl_ui_hanzify#8]
### **Keymap - Sequencer - Sequencer(Global) - Unmute Strips**
对照截图：
![Snipaste_2019-07-15_14-21-15](https://user-images.githubusercontent.com/35016284/61198368-49bbc780-a70c-11e9-95f1-630588413a71.png)
![Snipaste_2019-07-15_14-21-31](https://user-images.githubusercontent.com/35016284/61198369-4a545e00-a70c-11e9-9130-3d71b20226e1.png)
错误描述：
mute是【禁用】，所以Unmute统一成【取消禁用】比较好，【片断】是错字
修改建议：
【取消屏蔽片断】改成【取消禁用片段】

补充截图：
![Snipaste_2019-07-15_14-28-52](https://user-images.githubusercontent.com/35016284/61198598-437a1b00-a70d-11e9-9a13-f3010a71b620.png)
![Snipaste_2019-07-15_14-29-22](https://user-images.githubusercontent.com/35016284/61198602-470da200-a70d-11e9-9e1e-507295ee856b.png)
修改建议：
也是错字，【片断】改成【片段】

**Comment by sfire** [comment]
已提交修正 f9252ca33f17b9cd6c58f5fa6df6b4e4804c2da5
