### ISSUE TITLE
Keymap - Text - Text(Global)

### ISSUE THREAD

**Issue by dmmocn** [sfire/bl_ui_hanzify#9]
### **Keymap - Text - Text(Global) - Select Line**
对照截图：
![Snipaste_2019-07-15_14-44-35](https://user-images.githubusercontent.com/35016284/61199381-55a98880-a710-11e9-9fde-aaa256f0e91e.png)
![Snipaste_2019-07-15_14-44-45](https://user-images.githubusercontent.com/35016284/61199385-56dab580-a710-11e9-8f59-666bfa18e220.png)
错误描述：
翻译的小错误
修改建议：
【连接行号】改成【选择行】或者【选择当前行】
### **Keymap - Text - Text(Global) - Move Lines**
对照截图：
![Snipaste_2019-07-15_14-45-02](https://user-images.githubusercontent.com/35016284/61199433-88538100-a710-11e9-9853-b39a412555c8.png)
![Snipaste_2019-07-15_14-45-14](https://user-images.githubusercontent.com/35016284/61199434-88538100-a710-11e9-98f2-3fcef964c4f9.png)
错误描述：
Line在这里应该翻译成【行】，不是【线条】
修改建议：
【移动线条】改成【移动行】或者【移动当前行】
### **Keymap - Text - Text(Global) - Scrollbar**
对照截图：
![Snipaste_2019-07-15_14-45-56](https://user-images.githubusercontent.com/35016284/61199567-07e15000-a711-11e9-9a4c-7d4accee65e8.png)
![Snipaste_2019-07-15_14-46-04](https://user-images.githubusercontent.com/35016284/61199571-0b74d700-a711-11e9-821c-73b21d5a7229.png)
错误描述：
Scrollbar是【滚动条】
修改建议：
【滚动】改成【滚动条】

**Comment by sfire** [comment]
已提交修正 f9252ca33f17b9cd6c58f5fa6df6b4e4804c2da5
